/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

__attribute__((naked)) void init_scheduler_stack(uint32_t);
void init_tasks_stack();
void init_systick_timer(uint32_t);

uint32_t psp_of_tasks[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};
uint32_t task_handlers[MAX_TASKS];


int main(void)
{
    init_scheduler_stack(SCHD_STACK_START);

    task_handlers[0] = (uint32_t)task1_handler;
    task_handlers[1] = (uint32_t)task2_handler;
    task_handlers[2] = (uint32_t)task3_handler;
    task_handlers[3] = (uint32_t)task4_handler;

    init_tasks_stack();

	init_systick_timer(TICK_HZ);
	for(;;);
}


void task1_handler(){
	while(1){
		printf("This is task 1\n");
	}
}

void task2_handler(){
	while(1){
		printf("This is task 2\n");
	}
}

void task3_handler(){
	while(1){
		printf("This is task 3\n");
	}
}

void task4_handler(){
	while(1){
		printf("This is task 4\n");
	}
}

void init_systick_timer(uint32_t tick_hz){
	//systick reload value register, do NOT set CVR explicitly
	uint32_t *pSRVR = (uint32_t *)	0xE000E014;
	//subtract one because trigger happens on reload, not when CVR value hits 0
	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) -1;

	//clear value of pSVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//load value into
	*pSRVR |= count_value;

	//do some settings
	uint32_t *pSCSR = (uint32_t *)	0xE000E010;
	*pSCSR |= (1 << 1); //enable systick exception
	*pSCSR |= (1 << 2); //indicates clock source, in this case, processor clock instead of external


	//enable the systick
	*pSCSR |= (1 << 0); //systick counter start
}

void init_tasks_stack(void){
	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++){
		pPSP = (uint32_t *)psp_of_tasks[i];

		pPSP--;
		*pPSP = DUMMY_XPSR;

		pPSP--; //PC
		*pPSP = task_handlers[i];//0x00100000

		pPSP--;	//LR
		*pPSP = 0xFFFFFFFD;

		//zero out the other registers
		for(int j = 0; j < 13; j++){
			pPSP--;
			*pPSP = 0;
		}

		//preserve value of PSP
		psp_of_tasks[i] = (uint32_t)pPSP;
	}
}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){
	//must be assembly instruction to set MSP, it is the only arg, so already in RO
	__asm volatile("MSR MSP, %0" : : "r" (sched_top_of_stack) : );
	//BX copies the value of LR into PC to return to the calling function, there is no prologue or epilogue by default
	//should be read of "return from function call"
	__asm volatile("BX LR");
}

void SysTick_Handler(void){

}
